[package]
name = "cargo-fetcher"
version = "0.9.0"
authors = ["Embark <opensource@embark-studios.com>", "Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"
description = "🎁 Experimental alternative to cargo fetch"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/cargo-fetcher"
homepage = "https://github.com/EmbarkStudios/cargo-fetcher"
repository = "https://github.com/EmbarkStudios/cargo-fetcher"
keywords = ["fetch", "gcs", "s3"]
readme = "README.md"

[[bin]]
name = "cargo-fetcher"
path = "src/cmds/main.rs"

[dependencies]
anyhow = "1.0"
app_dirs2 = "2.0"
async-tar = "0.2"
async-trait = "0.1"
async-std = { version = "1.6.0", optional = true }
azure_sdk_core = { version = "0.43", optional = true }
azure_sdk_storage_blob = { version = "0.45", optional = true }
azure_sdk_storage_core = { version = "0.44", optional = true }
bytes = "0.5.4"
chrono = "0.4.10"
digest = { version = "0.9", optional = true }
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
futures = { version = "0.3.4" }
futures-util = { version = "0.3.4", features = ["async-await-macro"] }
hex = { version = "0.4.2", optional = true }
http = "0.2.0"
md5 = { version = "0.7", optional = true }
rayon = "1.3.0"
remove_dir_all = "0.5.2"
reqwest = { version = "0.10.1", default-features = false, features = ["rustls-tls"] }
ring = "0.16.11"
rusoto_core = { version = "0.45", default-features = false, features = ["rustls"], optional = true }
rusoto_s3 = { version = "0.45", default-features = false, features = ["rustls"], optional = true }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = { version = "1.0.1", optional = true }
sha2 = { version = "0.9", optional = true }
structopt = "0.3.9"
tame-gcs = { version = "0.7.0", optional = true }
tame-oauth = { version = "0.4.2", features = ["gcp"], optional = true }
tar = "0.4.26"
tempfile = "3.1.0"
toml = "0.5.6"
tracing = "0.1.12"
tracing-futures = "0.2.2"
tracing-subscriber = "0.2.1"
url = "2.1.1"
walkdir = "2.3.1"
zstd = "0.5.1"
cargo = "0.47.0"

[dependencies.tokio]
version = "0.2.13"
features = ["rt-threaded", "rt-util", "blocking", "process", "macros"]

[features]
default = []
fs = ["sha2", "async-std", "serde_json", "digest", "hex"]
gcs = ["tame-gcs", "tame-oauth"]
s3 = ["rusoto_core", "rusoto_s3"]
fs_test = ["fs"]
blob = ["azure_sdk_core", "azure_sdk_storage_core", "azure_sdk_storage_blob", "md5"]

[dev-dependencies]
difference = "2.0.0"
tempfile = "3.1.0"
twox-hash = "1.5.0"
walkdir = "2.3.1"

[[test]]
name = "sync_crates_io"
path = "tests/sync_crates_io.rs"
required-features = ["fs_test"]

[[test]]
name = "sync_git"
path = "tests/sync_git.rs"
required-features = ["fs_test"]

[[test]]
name = "diff_cargo"
path = "tests/diff_cargo.rs"
required-features = ["fs_test"]

[profile.dev.build-override]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
