[package]
name = "eg"
version = "0.1.0"
authors = ["m0ssc0de <hi.paul.q@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = { version = "0.1.0", registry = "my-registry" }

